//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControleVeiculoTCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculos
    {
        public System.Guid VeiculoId { get; set; }
        public System.Guid ClienteId { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Cor { get; set; }
        public Nullable<int> Ano { get; set; }
        public string Placa { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
